name: Print Version

on:
  workflow_dispatch:

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}


      - name: Determine version
        id: set-version
        run: |
          VERSION=$(python -c "import setuptools_scm; print(setuptools_scm.get_version(local_scheme='no-local-version'))")
          if [ "${{ github.event_name }}" != "release" ]; then
            VERSION="$VERSION.dev${{ github.run_number }}"
          fi
          echo "VERSION=$VERSION"
