name: Deploy to TestPyPI and PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tests:
    uses: darwinhc/bisslog-core-py/.github/workflows/pytest.yml@master
    with:
      coverage_threshold: ${{ vars.TEST_COVERAGE_THRESHOLD }}

  run-linter:
    uses: darwinhc/bisslog-core-py/.github/workflows/pylint.yml@master
    with:
      pylint_threshold: ${{ vars.PYLINT_THRESHOLD }}

  run-complexity:
    uses: darwinhc/bisslog-core-py/.github/workflows/radon.yml@master
    with:
      radon_threshold: ${{ vars.RADON_THRESHOLD }}

  deploy:
    runs-on: ubuntu-latest
    needs: [run-tests, run-linter, run-complexity]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*

      - name: Install from TestPyPI to verify
        run: |
          python -m venv test_env
          source test_env/bin/activate
          python -m pip install --index-url https://test.pypi.org/simple/ --no-deps bisslog
          deactivate
      - name: Publish to PyPI
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

