name: Deploy to TestPyPI and PyPI

on:
  release:
    types: [published]
jobs:
  run-tests:
    uses: ./.github/workflows/pytest.yml

  run-linter:
    uses: ./.github/workflows/pylint.yml
    needs: run-tests

  run-radon:
    uses: ./.github/workflows/radon.yml
    needs: run-tests

  deploy:
    runs-on: ubuntu-latest
    needs: [run-tests, run-linter, run-radon]  # Solo publica si los otros jobs pasan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*

      - name: Install from TestPyPI to verify
        run: |
          python -m venv test_env
          source test_env/bin/activate
          python -m pip install --index-url https://test.pypi.org/simple/ --no-deps bisslog-core
          deactivate

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
